### ISSUE TITLE
Error with camel-spring-cloud-stream integration

### ISSUE THREAD

**Issue by nawres1** [donovanmuller/camel-spring-cloud-stream#2]
Hello i’m trying to integrate camel-spring-cloud-stream-starter in an existing project but I’m getting this error :
Any help plz!
![1](https://cloud.githubusercontent.com/assets/11133404/24793806/4e709220-1b7b-11e7-9cc4-f61ebe4cf2e1.PNG)
![2](https://cloud.githubusercontent.com/assets/11133404/24793915/ac304158-1b7b-11e7-8425-382dd4ec8543.PNG)

**Comment by donovanmuller** [comment]
@nawres1 Could please try with the 0.12 release?

```xml
<dependency>
    <groupId>io.switchbit</groupId>
    <artifactId>camel-spring-cloud-stream-starter</artifactId>
    <version>0.12</version>
</dependency>
```

**Comment by nawres1** [comment]
Thank you for your quick answer, the 0.12 release resolve very well this problem.
But I’m getting another problem : The dependencies of some of the beans in the application context form a cycle.
![3](https://cloud.githubusercontent.com/assets/11133404/24794958/8348ef66-1b7f-11e7-9668-46e11010c14d.PNG)

I want to mention I’m actually working with : spring-cloud-stream. And the existing code was working very well before I’m adding : camel-spring-cloud-stream-starter
Should I remove :spring-cloud-stream from my dependency ??

**Comment by donovanmuller** [comment]
`camel-spring-cloud-stream` already brings in [`spring-cloud-stream`](https://github.com/donovanmuller/camel-spring-cloud-stream/blob/master/camel-spring-cloud-stream/pom.xml#L24), so you should remove your inclusion of sc-stream.

Also, what version of `spring-cloud-stream` are you using?
The 0.12 release is based on [`Brooklyn.SR2`](https://github.com/donovanmuller/camel-spring-cloud-stream/blob/master/pom.xml#L33).

See the [sample project](https://github.com/donovanmuller/camel-twitter-stream) for reference.

**Comment by donovanmuller** [comment]
BTW, I noticed that you are using Spring Boot 1.5.2, so I have updated `camel-spring-cloud-stream` dependencies to the latest (#3) and released [0.13](https://bintray.com/donovanmuller/switchbit-public/camel-spring-cloud-stream/0.13). Perhaps you'd like to use the latest version...

**Comment by donovanmuller** [comment]
@nawres1 Did you solve your issue?

**Comment by nawres1** [comment]
I'm overwhelmed with work in this period , but i will test it ASAP

**Comment by donovanmuller** [comment]
Closed due to inactivity
